language: android

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-18
env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=10

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell date -s `date +"%Y%m%d.%H%M%S"`
  - adb shell input keyevent 82

script:
  - ./gradlew clean connectedAndroidTest --stacktrace
  - ./gradlew dependencyUpdates
